spring:
  application:
    name: backend-assignment-taskapi

  mvc:
    problemdetails:
      enabled: true

  jpa:
    open-in-view: false
    properties:
      hibernate.jdbc.time_zone: UTC

# define mysql properties here
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:taskdb}?serverTimezone=UTC
    username: ${DB_USERNAME:taskuser}
    password: ${DB_PASSWORD:taskpass}
# define redis properties here

# define rocketmq properties here