spring:
  application:
    name: backend-assignment-taskapi

  jpa:
    open-in-view: false
    properties:
      hibernate.jdbc.time_zone: UTC

  # define mysql properties here
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306
    username: ${DB_USERNAME:taskuser}
    password: ${DB_PASSWORD:taskpass}
# define redis properties here

# define rocketmq properties here