server:
  port: ${APP_SERVER_PORT:8080}

spring:
  application:
    name: backend-assignment-taskapi

  mvc:
    problemdetails:
      enabled: true

  jpa:
    open-in-view: false
    properties:
      hibernate.jdbc.time_zone: UTC

  datasource:
    # define mysql properties here
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:taskdb}?serverTimezone=UTC
    username: ${DB_USERNAME:taskuser}
    password: ${DB_PASSWORD:taskpass}
# define redis properties here
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      database: 0

# define rocketmq properties here
rocketmq:
  namesrvAddr: ${NAMESRV_ADDR:localhost:9876}

  producer:
    group: task-trigger-group
    topic: task-schedule-topic